### ISSUE TITLE
Shortcomings with the release of version 4.0.0

### ISSUE THREAD

**Issue by harriha** [winjs/winjs#963] opened 2015-03-17 13:01 UTC
Hi,

It seems that http://try.buildwinjs.com is using version 4.0.0, but what's available via npm/bower/CDN is 3.0.1. I think it would be good to keep these in sync, to avoid confusion among developers looking at one thing on that site and then getting something else when fetching the library.

Also, related to this: it might be a good idea to show the currently used version explicitly on the http://try.buildwinjs.com/ site (and even provide the release history with dates and links to corresponding git tags).

Furthermore, regarding the git tags, the release 4.0.0 hasn't apparently been tagged (not visible under 'releases'), and therefore there's no clear way to obtain that version of the library.

I understand that the actual release of this latest version of the library might be work-in-progress, but thought to list the issues I currently see here anyway, just in case they are not known.

**Comment by xirzec** [comment] 2015-03-17 17:52
Hi @harriha 

We haven't released 4.0.0 yet, though the preview version of it should be out shortly. At that time you'll be able to see both on the Get page.

We do actually show the version of WinJS used on the Try site, though it is hard to find. You can see it near the bottom of this page:

http://try.buildwinjs.com/#status

Not sure why it's there, it should probably be on the Get page. Also I don't think the commit id is correct since we're probably on the Preview branch currently. @rigdern Can you comment on this?

**Comment by harriha** [comment] 2015-03-17 19:48
Ok, thanks for clarifications. The main point I had was just the mismatch between what's shown on the Try site and what's available via npm etc. I understand that it makes sense to show the latest stuff on the Try site, but if the same stuff is not available (easily) for development, things can get confusing. At least my initial assumption would be that I can get the same stuff I see on that site with `npm install winjs`.

But anyway, looking forward to seeing 4.0.0 being officially out, I can leave these release-related issues for you to chew them over as you see best.

**Comment by rigdern** [comment] 2015-03-18 17:46
Dupe of #827

**Closed by rigdern** 2015-03-18 17:46 UTC
Labels: resolution: duplicate

**Comment by rigdern** [comment] 2015-03-18 18:48
The Try Site is now demoing WinJS from our 4.0-preview branch as can be seen from the link to the git commit the site is using at the bottom of http://try.buildwinjs.com/#status:

![image](https://cloud.githubusercontent.com/assets/199935/6716695/717dfdc8-cd64-11e4-86be-ba8c466f5043.png)
