### ISSUE TITLE
Click on input field sets no cursor

### ISSUE THREAD

**Issue by NCC1701M** [winjs/winjs#896] opened 2015-01-20 13:32 UTC
Hi,
I have several input fields in a div which is displayed as an inline-flex the flex-direction is column and it is wrapping. 
Inside the div there are several other divs with a <label /> and an <input type="text" /> each. 
When I click on an <input /> it gets the focus and the cursor. You can see the example here:
http://jsfiddle.net/a4fat0rh/

But when I use ui-dark.css (not other WinJS libs) and I click on an input only the inputs in the first column get the focus and the cursor. All other inputs don't get the cursor and you can't write. You have to click quit at the bottom or top of the Input so that they get the cursor. You can see the example here: http://jsfiddle.net/pkefzybz/1/

INFO: This problem appears in IE. It works with Firefox and Chrome. I use IE 11.0.9600.17501CO Update Version 11.0.15

**Comment by phosphoer** [comment] 2015-01-30 22:34
This seems to be caused by `-ms-user-select: none` in our stylesheet applied to `html, body`. Note that we have `-moz-user-select: none` and `-webkit-user-select: none` applied as well, so this is looking like an IE bug.

**Comment by phosphoer** [comment] 2015-01-30 22:57
I'm putting together a min repro here: http://codepen.io/phosphoer/pen/wBqbPV
It seems flexbox is required to get the repro.

**Comment by phosphoer** [comment] 2015-01-30 23:28
Closing this now as an external issue

**Closed by phosphoer** 2015-01-30 23:28 UTC
Labels: ..pri: 2, feature: intrinsiccontrols, platform: ie, resolution: external
