### ISSUE TITLE
Flyout, Menu when initialized with hidden = false is attempted to be shown after partially being initialized

### ISSUE THREAD

**Issue by yildirimcagri** [winjs/winjs#1333] opened 2015-08-05 00:14 UTC
These controls cannot be created as not hidden due to this bug as some properties are not set.

**Comment by AmazingJaze** [comment] 2015-08-05 00:26
dupe of https://github.com/winjs/winjs/issues/1233

**Closed by AmazingJaze** 2015-08-05 00:26 UTC
