### ISSUE TITLE
Hub: Add support for WP like old panorama

### ISSUE THREAD

**Issue by lorantd** [winjs/winjs#114] opened 2014-04-12 20:56 UTC
Xaml has new hub control for wp that is similar to the old panorama. Winjs hub should behave the same for wp.

**Comment by pke** [comment] 2015-04-20 18:55
Is this still on the list? The panorama control with its parallax background was nice to look at and a signature Windows Phone control.

**Comment by jayrenn** [comment] 2015-06-11 19:33
@pke For Windows 10, in both XAML and WinJS, the parallax and carousel functionality have been removed from this control. Closing this as by design.

**Closed by jayrenn** 2015-06-11 19:33 UTC
Labels: .kind: featurerequest
