### ISSUE TITLE
Pivot: Arrow buttons have box glyphs on Mac

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#967] opened 2015-03-18 21:23 UTC
![screen shot 2015-03-18 at 2 22 34 pm](https://cloud.githubusercontent.com/assets/199935/6719771/4de38c28-cd7a-11e4-8aa6-a64dd116f681.png)

Note that FlipView's arrow buttons have the expected glyphs.

**Comment by jseanxu** [comment] 2015-03-20 19:01
Dupe of #811

**Closed by jseanxu** 2015-03-20 19:01 UTC
Labels: .kind: codebug, feature: pivot
