### ISSUE TITLE
Splitview simple don't work.

### ISSUE THREAD

**Issue by vitorgrs** [winjs/winjs#933] opened 2015-02-17 22:18 UTC
I'm trying to create a splitview (with the latest version of WinJS 4.0 "Alpha"), but it simple don't work.
Give me error
![qff](https://cloud.githubusercontent.com/assets/9909446/6238373/b373be14-b6e1-11e4-8e8e-9a680eb3b685.PNG)

**Comment by rigdern** [comment] 2015-02-18 05:57
Can you provide a page/app that repros this bug? You can share the reduced repro on OneDrive as described on our [wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS#sharing-videos-and-full-code-samples) (look at the "Sharing Videos and full Code Samples" section).

**Comment by rigdern** [comment] 2015-02-19 01:16
Looks like a dupe of #936

**Closed by rigdern** 2015-02-19 01:16 UTC
Labels: resolution: duplicate
