### ISSUE TITLE
AppBar: Issues related to the secondary buttons and appbar layout

### ISSUE THREAD

**Issue by catchspider2002** [winjs/winjs#1353] opened 2015-08-14 18:27 UTC
Feature: AppBar
Environment: Windows 10 UWP
Source: http://try.buildwinjs.com v4.1.0

1. When the AppBarCommand is in the secondary section or when the primary commands overflow into the secondary section, the onclick event handler does not work for the secondary commands.

2. When the command is localized as provided in this link - https://msdn.microsoft.com/en-us/library/windows/apps/JJ673579.aspx, it does not show up any label in the secondary section. The only workaround was to create separate html files for each language.

3. When there are no commands in the secondary section, the ellipsis is not displayed, so the appbar cannot be expanded to display the labels.

4. The hidden property for appBarCommand works only for the primary section, the secondary section still shows the hidden commands

5. When the SplitView ClosedDisplayMode is set as inline, the appbar moves to the right and the ellipsis button and half of the last icon is cut off from the screen.

**Comment by AmazingJaze** [comment] 2015-08-19 07:36
Hi @catchspider2002, thank you for the detailed bug report.

1) I believe this is the same duplicate issue as https://github.com/winjs/winjs/issues/1196 && https://github.com/winjs/winjs/issues/1197. If you use the onclick property on the AppBarCommand object itself,  instead of the AddEventListener API the click behavior should work correctly no matter where the AppBarCommand is located.
```js
var cmdViewFavs = document.getElementById('cmdMyFavorites');
cmdViewFavs.winControl.onclick = ("click", function(){
   console.log('cmdViewFavs clicked!');
});
```
Please let me know if you are able to resolve the click handler issue with that, and I will reopen 1197, a separate bug just to track this behavior.

2) I have filed a separate issue to track this behavior #1375. The issue with both 1. and 2. is that we are using proxy elements to represent the AppBarCommand in the overflow area and not all properties and attributes are getting carried over. Please use #1375 to track this issue moving forward.

3) is a dupe of https://github.com/winjs/winjs/issues/982 which was fixed in our master branch last week and will be available as a part of WinJS 4.2 which we are currently in the process of releasing.

4) I was unable to repro on a recent build of WinJS. For instance:

```HTML
<div id =”myAppBar” data-win-control=”WinJS.UI.AppBar” data-win-options=”{}” >
   <button data-win-control=”WinJS.UI.Command” data-win-options=”{label: ‘add', icon: ’add’ }” >

   </button>

   <button data-win-control=”WinJS.UI.Command” data-win-options=”{label: ‘delete, icon: ’delete’, section: 'secondary’, hidden: true }” >

   </button>
</dv>

```

The secondary command is not visible when I open the AppBar. If I then do
```JS
  var appBar = document.getElementById(“myAppBar”).winControl;

  appBar.data.getAt(1).hidden = false;l // The command appears in the overflow area
```
 likewise,

```JS
  var appBar = document.getElementById(“myAppBar”).winControl;

  appBar.data.getAt(1).hidden = true;l // The command hides from the overflow area
```
If you use a recent version of WinJS, do you still see the issue or has it gone away?

5) When you see this behavior, are you placing the AppBar inside of the SplitView? Can you share an HTML snippet that I could use to reproduce this exact behavior?

**Comment by AmazingJaze** [comment] 2015-08-19 07:38
updated

**Comment by AmazingJaze** [comment] 2015-09-01 01:32
For now due to inactivity. If you are still having issues with (4) or (5) using the latest version of WinJS, please open a new issue and reference this one.

**Closed by AmazingJaze** 2015-09-01 01:32 UTC
Labels: ..pri: 1, .kind: codebug, feature: appbar
