### ISSUE TITLE
[High contrast] Buttons always visually appear that they are in the rest state

### ISSUE THREAD

**Issue by jayrenn** [winjs/winjs#1346] opened 2015-08-13 21:19 UTC
The buttons do not appear to change when in other states. They always look like they’re in the rest state. Should be:
![image](https://cloud.githubusercontent.com/assets/7266075/9261948/42e20e74-41c6-11e5-9403-0555f14ccea8.png)

**Comment by rigdern** [comment] 2015-08-28 23:23
dupe of #1259.

**Closed by rigdern** 2015-08-28 23:23 UTC
Labels: ..pri: 1, .kind: codebug, feature: accessibility
