### ISSUE TITLE
SearchBox: Cannot instantiate a searchbox that is initially disabled

### ISSUE THREAD

**Issue by TheWrathOfConst** [winjs/winjs#900] opened 2015-01-23 19:47 UTC
This will throw an exception in WinJS.UI.SearchBox._disableControl:
```html
    <div data-win-control="WinJS.UI.SearchBox" data-win-options="{disabled: true}"></div>
    <script>
        WinJS.UI.processAll();
    </script>
```
This is the faulting line of code:

```js
                    this._buttonElement.disabled = true;
```
 _buttonElement is null at the time _setOptions is called by the SearchBox constructor.

**Comment by rigdern** [comment] 2015-01-24 02:17
#### Cause

The problem is due to how the `SearchBox` and `AutoSuggestBox` coordinate during construction.

The problem is that, in the middle of its constructor, `SearchBox` calls `AutoSuggestBox`'s constructor and `AutoSuggestBox`'s constructor calls `SearchBox`'s `disableControl` (via `_setOptions` because `disabled` is listed in the options) method but `SearchBox` hasn't completed initialization yet. Consequently, `SearchBox`'s `_buttonElement` is null which leads to the exception.

#### A Similar Bug

This is similar to the bug fixed by https://github.com/winjs/winjs/commit/d5fe7e1e4fe91984d6e18c4a181f9f42b5906d96#diff-f2cb9b0661ef719d6777772a2aa01747. The bug there occurred when passing `focusOnKeyboardInput` in the options. This would cause `SearchBox`'s `focusOnKeyboardInput` setter to run before `SearchBox` had created the bound versions of its events.

#### General Problem and Fix

Perhaps we can find a more general fix this time. The general problem is that `SearchBox`'s constructor wants `AutoSuggestBox`'s constructor to run before `SearchBox` finishes initializing itself. However, `AutoSuggestBox`'s constructor might run `SearchBox` code and `SearchBox` isn't done initializing yet. Both times this happened via `_setOptions`.

Perhaps `SearchBox` should call `_setOptions` instead of `AutoSuggestBox`. `AutoSuggestBox`'s constructor can take a private flag to disable its `_setOptions` call.

**Comment by TheWrathOfConst** [comment] 2015-02-23 20:53
When this bug is fixed, please uncomment the angular-winjs searchbox unit test that was hitting this bug ( see https://github.com/winjs/angular-winjs/blob/master/tests/SearchBox.js )

**Closed** 2015-04-13 23:25 UTC
Labels: ..pri: 1, .kind: codebug, feature: searchbox
