### ISSUE TITLE
Ignore right-click for dragging, it conflit with context menu.

### ISSUE THREAD

**Issue by derek1ee** [winjs/winjs#1154] opened 2015-05-18 18:58 UTC
Context menu is invoked with right click, but at the same time, right click also drags an item.

Often, user intend to see context menu, but mouse moves slightly while right click, causing the item to be dragged, and context menu will not show.

**Comment by rigdern** [comment] 2015-05-20 22:16
@TheWrathOfConst: Can this be resolved by the app by preventing default on the HTML 5 drag and drop events on the ListView?

**Comment by derek1ee** [comment] 2015-05-20 22:19
We do still want to support drag-and-drop, but just on left-click-and-hold, in which does not interfere with context menu.

**Comment by TheWrathOfConst** [comment] 2015-05-21 00:56
The app can prevent drag on right mouse by setting up an event handler on pointerdown and an event handler on dragstart. I've written up this sample to show how it can be done:

```js
// Boilerplate sample ListView
        var data = [1, 2, 3, 4, 5, 6];
        var listView = new WinJS.UI.ListView();
        listView.itemDataSource = new WinJS.Binding.List([1, 2, 3, 4, 5, 6]).dataSource;
        listView.selectionMode = "none";
        listView.tapBehavior = "none";
        listView.itemsDraggable = true;
        document.body.appendChild(listView.element);
// end of boilerplate

        var lastPointerWasRightMouse = false;
        WinJS.Utilities._addEventListener(listView.element, "pointerdown", function (event) {
            lastPointerWasRightMouse = (event.pointerType === "mouse" && event.buttons === 2);
        });
        listView.addEventListener("dragstart", function (e) {
            if (lastPointerWasRightMouse) {
                e.preventDefault();
                e.stopPropagation();
            }
        }, true);
```

**Comment by rigdern** [comment] 2015-05-22 18:58
Resolving by design

**Closed by rigdern** 2015-05-22 18:58 UTC
Labels: ..pri: 1, ..status: investigate, .kind: codebug, feature: listview, resolution: by design
